version: '{branch}~{build}'
clone_depth: 10

platform:
- x64

image:
- Visual Studio 2017

environment:
  CYGMIRROR: http://ftp.inf.tu-dresden.de/software/windows/cygwin32
  matrix:
  - USEOPAM: true
    ARCH: 64

build_script:
- cmd: 'call %APPVEYOR_BUILD_FOLDER%\dev\ci\appveyor.bat'

test: off
